### ISSUE TITLE
API key is null

### ISSUE THREAD

**Issue by Jozefw** [google/chatbase-node#3]
Getting this error for the demo:

/Users/jozefw/Desktop/chatbase-codelab-io-2017-master/node_modules/@google/chatbase/lib/MessageFactory.js:118
  newMessage (apiKey=null, userId=null) {
                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jozefw/Desktop/chatbase-codelab-io-2017-master/node_modules/@google/chatbase/lib/ApplicationInterface.js:19:24)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by cristiancavalli** [comment]
Hey @Jozefw please make sure you are using Node V6+ while using this library. Thanks for pointing this out though -- will update the codelab and package.json accordingly.

To see which version you have currently installed you can use the following command:
`node -v`

If this doesn't help please lmk.

Thanks,
Cris

**Comment by cristiancavalli** [comment]
Engine field has been updated in e63242d80477170f708d7addd1df3d8c73d097fc

**Comment by Jozefw** [comment]
Chris,
thanks for your speedy reply.

Took some time to get the most recent install of node in place as node 4.1 kept 
persisting.  I installed the node pkg and it went well.

will see if this works tomorrow.

Thanks again,
btw, I clicked on your link in github that took me to the youtube page “this goes up to 11”
NICE!

Jozef
